name: üöÄ publish directory1

on:
  push:
    branches: ['main']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-deploy-directory1:
    runs-on: ubuntu-latest
    steps:
      - name: üìÇ Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine modified directory 1 (Python)
        id: determine_directory1_python
        uses: ./.github/workflows/determine-modified-directory-python
        with:
          directory: 'directory1'


      # - name: üöÄ Determine modified directory 1
      #   id: determine_directory1
      #   run: |
      #     git diff --name-only HEAD~1 ${{ github.sha }} > changes.txt
      #     if grep -q '^directory1/' changes.txt; then
      #       echo "Directory 1 has changes"
      #       echo "::set-output name=directory::directory1"
      #     else
      #       echo "No changes in Directory 1"
      #       exit 0
      #     fi

      - name: üîå Login to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: steps.determine_directory1.outputs.directory == 'directory1'

      - name: üèóÔ∏è Build and ü´∏ push image to GitHub Container Registry for Directory 1
        uses: docker/build-push-action@v5
        with:
          context: ${{ steps.determine_directory1.outputs.directory }}
          push: true
          tags: ghcr.io/leahlandau/try-directory1:latest
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: steps.determine_directory1.outputs.directory == 'directory1'

      # - name: üîå Login to Azure
      #   uses: azure/login@v1
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure Login
        run: az login 
        if: steps.determine_directory1.outputs.directory == 'directory1'

      - name: üöÄ Deploy Function App for Directory 1
        uses: azure/functions-action@v1
        with:
          app-name: ${{ secrets.AZURE_APP_NAME_DIRECTORY1 }}
          package: ${{ github.workspace }}/directory1/
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE_DIRECTORY1 }}
        if: steps.determine_directory1.outputs.directory == 'directory1'
