name: ğŸš€ Publish Directories

on:
  push:
    branches: ['main']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory:
          - directory4
          # - directory2

    steps:
      - name: ğŸ“‚ Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ğŸ” Determine modified directory
        id: determine_directory
        run: |
          git diff --name-only HEAD~1 ${{ github.sha }} > changes.txt
          if grep -q '^${{ matrix.directory }}/' changes.txt; then
            echo "${{ matrix.directory }} has changes"
            echo "::set-output name=directory::${{ matrix.directory }}"
          else
            echo "No changes in ${{ matrix.directory }}"
            exit 0
          fi
      - name: ğŸ”‘ Login to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: steps.determine_directory.outputs.directory == matrix.directory

      - name: ğŸ”– Get release tag name
        id: get_release
        uses: cardinalby/git-get-release-action@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          latest: true
        if: steps.determine_directory.outputs.directory == '${{ matrix.directory }}'

      - name: â™»ï¸ Set correct environment
        run: |
          TAG=${{ steps.get_release.outputs.tag_name }}
          echo "TAG=$TAG" >> "$GITHUB_ENV"
        if: steps.determine_directory.outputs.directory == '${{ matrix.directory }}'

      - name: ğŸ³ Docker metadata
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/leahlandau/try-${{ matrix.directory }}
          tags: |
            type=semver,pattern={{major}}.{{minor}}.{{patch}},value=${{ env.TAG }}
            type=semver,pattern={{major}}.{{minor}},value=${{ env.TAG }}
            type=semver,pattern={{major}},value=${{ env.TAG }}
        if: steps.determine_directory.outputs.directory == '${{ matrix.directory }}'

      - name: ğŸ—ï¸ Build and ğŸ«¸ push image to GitHub Container Registry
        uses: docker/build-push-action@v5
        with:
          context: ${{ steps.determine_directory.outputs.directory }}
          push: true
          tags: ghcr.io/leahlandau/${{ matrix.directory }}:latest
          labels: ${{ steps.docker_meta.outputs.labels }}
        if: steps.determine_directory.outputs.directory == matrix.directory

      # - name: ğŸ”Œ Login to Azure
      #   uses: azure/login@v1
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Azure Login
        run: az login 
        if: steps.determine_directory.outputs.directory == matrix.directory 

      - name: ğŸš€ Deploy to Azure Function App
        uses: Azure/functions-container-action@v1
        with:
          app-name: directory4
          image: ghcr.io/leahlandau/try-${{ matrix.directory }}
         
