name: ğŸš€ publish directory10

on:
  push:
    branches: ['main']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-deploy-directory1:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“‚ Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0


      - name: ğŸ” Determine modified directory 1
        id: determine_directory1
        run: |
          git diff --name-only HEAD~1 ${{ github.sha }} > changes.txt
          if grep -q '^directory1/' changes.txt; then
            echo "Directory 1 has changes"
            echo "::set-output name=directory::directory1"
          else
            echo "No changes in Directory 1"
            exit 0
          fi

      - name: ğŸ”‘ Login to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        # if: steps.determine_directory1.outputs.directory == 'directory1'
 

      - name: ğŸ”– Get release tag name
        id: get_release
        uses: cardinalby/git-get-release-action@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          latest: true
        # if: steps.determine_directory1.outputs.directory == 'directory1'

      - name: â™»ï¸ Set correct environment
        run: |
            TAG=${{ steps.get_release.outputs.tag_name }}
            echo "TAG=$TAG" >> "$GITHUB_ENV"
        # if: steps.determine_directory1.outputs.directory == 'directory1'

      - name: ğŸ³ Docker metadata
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/leahlandau/try-directory1
          tags: |
                type=semver,pattern={{major}}.{{minor}}.{{patch}},value=${{ env.TAG }}
                type=semver,pattern={{major}}.{{minor}},value=${{ env.TAG }}
                type=semver,pattern={{major}},value=${{ env.TAG }}
          # if: steps.determine_directory1.outputs.directory == 'directory1'
      
      - name: ğŸ—ï¸ Build Image 
        uses: docker/build-push-action@v5
        with: 
          context: ${{ steps.determine_directory1.outputs.directory }}
          tags: ${{ steps.get_release.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}  
        # if: steps.determine_directory1.outputs.directory == 'directory1'
      # - name: ğŸ”‘ Login to Azure
      #   uses: azure/login@v1
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: ğŸ”‘ Azure Login
        run: az login 
        # if: steps.determine_directory1.outputs.directory == 'directory1'

      - name: ğŸš€ Deploy Function App for Directory 1
        uses: azure/functions-action@v1
        with:
          app-name: ${{ secrets.AZURE_APP_NAME_DIRECTORY1 }}
          package: ${{ github.workspace }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE_DIRECTORY10 }}
        # if: steps.determine_directory1.outputs.directory == 'directory1'
