name: 'üåç Terraform Automation'

on:
  workflow_dispatch:


env:
  TF_VAR_subscription_id: ${{secrets.SUBSCRIPTION_ID}}
  TF_VAR_RECIPIENT_EMAIL: ${{secrets.RECIPIENT_EMAIL}}
  TF_VAR_SHELIS_EMAIL: ${{secrets.SHELIS_EMAIL}}
  TF_VAR_DOCKER_REGISTRY_SERVER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  TF_VAR_DOCKER_REGISTRY_SERVER_USERNAME: ${{ github.actor }}
  TF_VAR_DOCKER_REGISTRY_SERVER_URL: https://ghcr.io
  ARM_SUBSCRIPTION_ID: ${{secrets.SUBSCRIPTION_ID}}
  ARM_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
  ARM_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
  ARM_CLIENT_SECRET: ${{secrets.AZURE_CLIENT_SECRET}}
  
jobs:
  job1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory:
          - emails
          - subscriptions-automation


    steps:
      - uses: actions/checkout@v3

      - name: üß© HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.0
      
      - name: üîë Login to Azure
        id : az-login
        run : az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID  

      - name: üèóÔ∏è Terraform Init
        id: init
        run: |
          cd ${{ matrix.directory }}/terraform  
          terraform init -input=false

      - name: üìã Terraform Plan
        id: plan
        run: |
          cd ${{ matrix.directory }}/terraform   
          terraform plan -out=tfplan -input=false

      - name: ‚úÖ Terraform Apply
        id: apply
        run: |
          cd ${{ matrix.directory }}/terraform    
          terraform apply -input=false -auto-approve tfplan

# 