name: ðŸ§ª Run Python tests

on:
  push:
    branches: 
      - main
      - development
      - feature/*
    paths: 
      - services/**
  pull_request:
    branches: 
      - main
      - development
      - feature/*
    paths: 
      - services/**

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./services
    strategy:
      matrix:
        python-version: ['3.10.13']
        
    steps:
    - name: ðŸ“‚ Checkout
      uses: actions/checkout@v3

    - name: ðŸ Set up Python 3.10.13
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: ðŸ Export environment
      run: |
        export CONTAINER=TEST

    - name: â¬ Install dependencies
      run: |
          pip install -r requirements.txt

    - name: list sub-directories
      id: sub-directories
      run: echo "DIRS=$(ls -d services/*/*/ | jq --raw-input --slurp --compact-output 'split("\n")[:-1]')" >> ${GITHUB_ENV}
      
    - name: âœ… Run tests
      run: |
        for dir in "${ ${{ env.DIRS}}[@]}"; do
          pytest dir
        done